name: moodtracker_app
description: an mood tracker app using ai models
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  animated_splash_screen: ^1.3.0
  flutter_svg: ^2.1.0
  google_fonts: ^6.2.1
  dartz: ^0.10.1
  supabase: ^2.7.0
  supabase_flutter: ^2.9.0
  get_it: ^8.0.3
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  flutter_dotenv: ^5.2.1
  loading_animation_widget: ^1.3.0
  shared_preferences: ^2.5.3
  camera: ^0.11.1
  image_picker: ^1.1.2
  tflite_flutter: ^0.11.0
  image: ^4.5.4
  permission_handler: ^12.0.0+1
  lottie: ^3.3.1
  tflite_v2: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - assets/models/emotion_model.tflite
    - assets/models/emotion_model_rgb.tflite
    - assets/models/labels.txt
    - assets/lottie/camera_loading.json
    - .env

flutter_assets:
  assets_path: assets/
  output_path: lib/core/constants/
  filename: logo_assets.dart


fonts:
  -  family: Inter
     fonts:
      - asset: assets\fonts\Inter_24pt-Regular.ttf
      - asset: assets\fonts\Inter_24pt-Medium.ttf
        weight: 500
      - asset: assets\fonts\Inter_24pt-SemiBold.ttf
        weight: 600
      - asset: assets\fonts\Inter_24pt-Bold.ttf
        weight: 700
    